### ISSUE TITLE
Include ability to change script to classical/western

### ISSUE THREAD

**Issue by SargisYonan** [SargisYonan/Mamlal#7]

**Comment by esoleyman** [comment]
I have this almost completed in my local repository but I'm running into an issue where the dropdown / select options are not being affected by document.body.style.fontFamily

**Comment by SargisYonan** [comment]
are you able to push your branch to this repo? I believe I gave the permission

**Comment by esoleyman** [comment]
I've tried but I think it's due to the deployment permissions

**Comment by esoleyman** [comment]
[switch-script.txt](https://github.com/SargisYonan/Mamlal/files/8110720/switch-script.txt)

**Comment by esoleyman** [comment]
Needs to have the SertoJerusalem fonts added to /public/fonts/
